-- Generated from generator/demo_specs/aws-vietnam-textile-production.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-vietnam-textile-production
-- This is the schema that is actually deployed for VIETNAM_TEXTILE_PRODUCTION.

-- Alerts fire on the bottom tail of Line Efficiency
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_LINE_EFFICIENCY) AS T
  FROM RAW.METRICS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_LINE_EFFICIENCY <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_LINE_EFFICIENCY), 2) AS AVG_LINE_EFFICIENCY,
  ROUND(AVG(f.KPI_QUALITY_PASS_RATE), 2) AS AVG_QUALITY_PASS_RATE,
  ROUND(AVG(f.KPI_SAM_ACHIEVEMENT), 2) AS AVG_SAM_ACHIEVEMENT,
  ROUND(AVG(f.KPI_CHANGEOVER_TIME), 2) AS AVG_CHANGEOVER_TIME,
  ROUND(AVG(f.KPI_ABSENTEEISM), 2) AS AVG_ABSENTEEISM
FROM RAW.METRICS f
JOIN RAW.DOCUMENTS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_LINE_EFFICIENCY), 2) AS AVG_LINE_EFFICIENCY,
  ROUND(AVG(f.KPI_QUALITY_PASS_RATE), 2) AS AVG_QUALITY_PASS_RATE,
  ROUND(AVG(f.KPI_SAM_ACHIEVEMENT), 2) AS AVG_SAM_ACHIEVEMENT,
  ROUND(AVG(f.KPI_CHANGEOVER_TIME), 2) AS AVG_CHANGEOVER_TIME,
  ROUND(AVG(f.KPI_ABSENTEEISM), 2) AS AVG_ABSENTEEISM
FROM RAW.METRICS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_LINE_EFFICIENCY) AS KPI_LINE_EFFICIENCY, AVG(KPI_QUALITY_PASS_RATE) AS KPI_QUALITY_PASS_RATE, AVG(KPI_SAM_ACHIEVEMENT) AS KPI_SAM_ACHIEVEMENT, AVG(KPI_CHANGEOVER_TIME) AS KPI_CHANGEOVER_TIME, AVG(KPI_ABSENTEEISM) AS KPI_ABSENTEEISM FROM RAW.METRICS),
     en AS (SELECT SUM(KPI_PRODUCTION_OUTPUT) AS KPI_PRODUCTION_OUTPUT, SUM(KPI_WORKERS_ACTIVE) AS KPI_WORKERS_ACTIVE FROM RAW.DOCUMENTS)
  SELECT 1 AS SORT_ORDER, 'Production Output' AS TITLE, KPI_PRODUCTION_OUTPUT AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_PRODUCTION_OUTPUT) / 1000000), 1) AS DECIMAL(38,1))) || 'M' || ' ' || 'pcs' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Line Efficiency' AS TITLE, KPI_LINE_EFFICIENCY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_LINE_EFFICIENCY)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Quality Pass Rate' AS TITLE, KPI_QUALITY_PASS_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_QUALITY_PASS_RATE), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Workers Active' AS TITLE, KPI_WORKERS_ACTIVE AS VALUE_NUM, LTRIM(TO_VARCHAR(CAST(ROUND((KPI_WORKERS_ACTIVE)) AS DECIMAL(38,0)), '999,999,999,999')) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'SAM Achievement' AS TITLE, KPI_SAM_ACHIEVEMENT AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SAM_ACHIEVEMENT)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Changeover Time' AS TITLE, KPI_CHANGEOVER_TIME AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CHANGEOVER_TIME), 1) AS DECIMAL(38,1))) || ' ' || 'hrs' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Absenteeism' AS TITLE, KPI_ABSENTEEISM AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ABSENTEEISM), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
